apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-htmlcoincore-regtest
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: htmlcoincore-regtest
    role: service
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   role: master
  #   tier: backend
  template:
    metadata:
      labels:
        app: htmlcoincore-regtest
        role: service
    spec:
      containers:
      - name: htmlcoincore-services
        image: ananseim/htmlcoincore-services:regtest
        imagePullPolicy: Always
        #resources:
          #requests:
            #cpu: 100m
            #memory: 100Mi
        ports:
        - containerPort: 3001
          name: http
        - containerPort: 14889
          name: http14889
#        env:
#          - name: http_port
#            value:  "4889"
#        command: ["/bin/htmlcoind && /bin/htmlcoin-cli"]
#        args: ["-testnet","-server","-debug","-printtoconsole","-rpcuser=user","-rpcpassword=password","-rest=1"]
