apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        # Create with
        # $ gcloud compute disks create --size 50GB --zone asia-southeast1-a mongo-storage
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          gcePersistentDisk:
            pdName: mongo-storage
            fsType: ext4
