apiVersion: v1
kind: Service
metadata:
  name: svc-htmlcoincore-regtest
  labels:
    app: htmlcoincore-regtest
    role: service
spec:
  type: LoadBalancer
  ports:
  -  port: 14889
     name: http14889
     targetPort: 14889
  -  port: 3001
     name: http3001
     targetPort: 3001
  selector:
    app: htmlcoincore-regtest
    role: service

